#!/bin/bash

# This script automates the creation of an EC2 compute instance

# Create administrator user on IAM, save keys
# Install dependencies
echo "Installing dependencies"
yum install -y epel-release
yum install -y awscli
# Configure awscli
echo "Input your administrator user credentials."
echo "Input the region us-east-1."
echo "Input text for the fourth option."
aws configure
# Create key pair
echo "Creating key pair"
aws ec2 create-key-pair --key-name keyPair --query 'KeyMaterial' --output text > keyPair.pem
# Change key pair permissions
echo "Changing keyPair.pem's permissions"
chmod 400 keyPair.pem
# Create security group
echo "Creating security group"
aws ec2 create-security-group --group-name secNode --description "Node security group"
# Set security group permissions
echo "Setting security group permissions"
aws ec2 authorize-security-group-ingress --group-name secNode --protocol tcp --port 22 --cidr 0.0.0.0/0
aws ec2 authorize-security-group-ingress --group-name secNode --protocol tcp --port 80 --cidr 0.0.0.0/0
aws ec2 authorize-security-group-ingress --group-name secNode --protocol tcp --port 3000 --cidr 0.0.0.0/0
# Run instance
echo "Spinning up the EC2 instance"
aws ec2 run-instances --image-id ami-6d1c2007 --count 1 --instance-type t2.micro --key-name keyPair --security-groups secNode
# Wait a bit for the instance to created
echo "Waiting a little bit for the dns to be configured"
sleep 10
# Get the public dns
echo ""
echo "The public dns of your EC2 instance is:"
aws ec2 describe-instances --query "Reservations[].Instances[].PublicDnsName"
echo ""
echo "SSH into the VM using the following command"
echo "ssh -l centos -i keyPair.pem <EC2 dns>"
echo ""
echo "When logged in, run the following command:"
echo "sudo -i; yum install -y git; git clone <repo>"
echo "Please allow some time for the instance to be created first."
echo ""
